version: '3.4'
name: friendship
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx:/etc/nginx/conf.d:ro
      - ./log:/var/log/nginx
    ports:
      - "80:80"
    depends_on:
      - backend
  backend:
    build: ./
    env_file:
      ./friendship/.env
    expose:
      - 8000
    depends_on:
      - postgres
    command: sh -c ./backend-entrypoint.sh
    restart: unless-stopped
  postgres:
    container_name: friendship-postgres
    image: postgres
    env_file:
      ./.env.db
    environment:
      PGDATA: "var/lib/postgresql/data/"
    expose:
      - 5432
    volumes:
      - .docker-volumes/postgres/data:/var/lib/postgresql/data/
    restart: unless-stopped
