# Generated by Django 4.2.1 on 2023-05-07 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FriendRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("CN", "consideration"), ("RJ", "reject")],
                        default="CN",
                        max_length=10,
                    ),
                ),
            ],
        ),
    ]
